# Generated by Django 3.1.3 on 2020-11-20 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notion', '0002_auto_20201121_0419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='name',
            field=models.CharField(max_length=1000),
        ),
    ]
