# Generated by Django 3.1.3 on 2020-11-22 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notion', '0004_post_mainphoto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='mainphoto',
            new_name='photo',
        ),
    ]
