# Generated by Django 3.1.3 on 2020-11-22 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notion', '0005_auto_20201122_2009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='auth',
        ),
        migrations.RemoveField(
            model_name='post',
            name='photo',
        ),
    ]
