# Generated by Django 3.1.3 on 2020-11-23 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notion', '0008_remove_post_pw'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='pw',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
