# Generated by Django 3.1.3 on 2020-11-23 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notion', '0009_post_pw'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='pw',
        ),
    ]
